### ISSUE TITLE
dataZoomSlider Event

### ISSUE THREAD

**Issue by kevin-hillyard** [bherbruck/svelte-echarts#10]
I have been unable to get the [dataZoom event](https://echarts.apache.org/en/api.html#events.datazoom) to trigger when using the slider. I have a single slider along the x-axis and when this slider moves I need to check if there are marklines that need to be updated. The marklines disappear if one of the points for the markline is not within the current zoom window (possibly its own issue) so I need to be able to update those if the slider is used to prevent the marklines from disappearing if they should still be visible.
In my attempts to capture the event I have tried the following.
`<Chart {options} on:dataZoom={handleDataZoom} />` This doesn't give me an error but the event never triggers. 
`<Chart bind:this={myChart} {options} />` Then I attempt to listen for the event with `myChart.on('dataZoom', handleDataZoom);` but this gives me an error saying the .on is not a function.
I got around this by attempting to use `myChart.$on('dataZoom', handleDataZoom);` which no longer gave an error but didn't ever catch the event.
I've also tried to add the event listener this way: `myChart.addEventListener('dataZoom', handleDataZoom);` but this gives me the same error but with .addEventListener is not a function.

My main question is whether the ability to catch the dataZoom event has been implemented into this library, and if so, what is the correct way to add a listener for it?
I did attempt changing the event name from "dataZoom" to "datazoom" as a precaution but the results were the same.

**Comment by bherbruck** [comment]
implemented in #18
