### ISSUE TITLE
cant install latest version v1.0.0-rc2

### ISSUE THREAD

**Issue by 0x090909** [bherbruck/svelte-echarts#21]
npm cant find the latest version during install, how can I update?

Thank you

**Comment by 0x090909** [comment]
<img width="791" alt="Screenshot 2024-06-18 at 16 31 53" src="https://github.com/bherbruck/svelte-echarts/assets/16927059/98752f6a-0f33-43bb-9fcd-3b9f79c6eb3a">

**Comment by bherbruck** [comment]
its good now: https://www.npmjs.com/package/svelte-echarts/v/1.0.0-rc2
