### ISSUE TITLE
Ability to modify one item inside chart.

### ISSUE THREAD

**Issue by 0x090909** [bherbruck/svelte-echarts#22]
Hello I would like to know which method to use to change the color of the selected item in this bar chart. 

I need to know which one has been selected and it to be clearly visible in the chart.

Thank you!

<img width="1254" alt="Screenshot 2024-06-26 at 10 16 38" src="https://github.com/bherbruck/svelte-echarts/assets/16927059/615944a2-537b-4de5-a954-c39c8307947b">

**Comment by bherbruck** [comment]
Id check out the official echarts docs for more info on how to do this.

**Comment by 0x090909** [comment]
I figured out
