### ISSUE TITLE
Can't install svelte-echarts with astro

### ISSUE THREAD

**Issue by Firaenix** [bherbruck/svelte-echarts#23]
Hi, 

I'd love to use your library, however while I install the package, it tries to run `svelte-kit sync` which I dont have installed.

I am using https://astro.build/ and as such dont have svelte-kit installed.

from the code, it doesnt seem like svelte-kit is required. Is it possible to install this library without having to install the svelte-kit CLI?

**Comment by bherbruck** [comment]
I will fix that, shortly, in the meantime you can run `npm install svelte-echarts --ignore-scripts`

**Comment by bherbruck** [comment]
fixed in https://github.com/bherbruck/svelte-echarts/commit/c5ca82970f0867486bdb3df460c44191c5984500

**Comment by Firaenix** [comment]
Amazing thanks so much! This is a great library!
