### ISSUE TITLE
Not sure how to implement the "Tree-shakeable" feature to reduce loading time

### ISSUE THREAD

**Issue by MuslemRahimi** [bherbruck/svelte-echarts#24]
Hi bherbruck,

I wanted to ask you if you can help me out how to implement the tree shakeable feature that you have implemented.

E.g. in my sveltekit component https://github.com/stocknear/frontend/blob/main/src/lib/components/DarkPool.svelte I plot a graph, where I want to import only files that are absolutely necessary to reduce loading time for the end user.

**Comment by bherbruck** [comment]
It looks like you're already doing it. Are you having an issue with your linked component?

**Comment by MuslemRahimi** [comment]
Sorry I resolved this issue myself. Thank you for the awesome library
