### ISSUE TITLE
Click Event for bar chart

### ISSUE THREAD

**Issue by MuslemRahimi** [bherbruck/svelte-echarts#3]
Hi,

I have a simple bar chart where i want to add a click event when the user clicks on one of the bars.

For example it should for now print "console.log('click received')".

Do you know a simple way to do this?

**Comment by DrStrangeloovee** [comment]
This [issue](https://github.com/bherbruck/svelte-echarts/issues/1) is related. Unfortunately I am currently not able to implement something more robust. But I left a comment which should help you in accessing the rest of the ECharts API.

**Comment by bherbruck** [comment]
implemented in [v1.0.0-rc1](https://github.com/bherbruck/svelte-echarts/releases/tag/v1.0.0-rc1)

**Comment by 0x090909** [comment]
how can I implement a click on a element, I cannot figure out

**Comment by hbcondo** [comment]
I ended up adding an `on:click` attribute to determine which bar was clicked:

```svelte
<Chart {init} {options} on:click={handleBarClick} />
```

```ts
function handleBarClick(params: any) {
  console.log(params.detail.name);
}
```
